### ISSUE TITLE
Is this going to be the source repo?

### ISSUE THREAD

**Issue by m4rc1e** [skosch/CrimsonProS#1]
Is this repo going to be the source repo?

If so, I'll master @FontHausen's files and pr them here. His [repo](https://github.com/Fonthausen/Crimson) is a fork of your original Crimson Repo.

cc @skosch @davelab6 @FontHausen

**Comment by skosch** [comment]
No no no no, this is just my personal playground because. I wanted to see what different variations of the font might look like. The real deal is @Fonthausen's Crimson repo. (Unless you want to publish both, but they're not the same thing)

**Comment by m4rc1e** [comment]
Thanks! 

Will we pr @Fonthausen's work to your repo https://github.com/skosch/Crimson?

I read a comment that you'll keep the legacy Crimson in a new branch?

**Comment by skosch** [comment]
That's one option, but since we've named this new one "Crimson Pro", and it really is @Fonthausen's work, his repo could remain the official upstream (and I'll just link to it from my old Crimson README). Maybe he can rename his repo to Crimson Pro instead and we can call it a day?

**Comment by Fonthausen** [comment]
If you want me to change the name or something else, I am open for it.

**Comment by skosch** [comment]
My suggestion would simply be to rename your repo to Crimson Pro (because that's what it is), and I'll link to it from my old Crimson repo. That would most accurately reflect reality.

**Comment by Fonthausen** [comment]
I renamed my repo to CrimsonPro.

https://github.com/Fonthausen/CrimsonPro

**Comment by m4rc1e** [comment]
Thanks all.
